apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector
  namespace: monitoring
  labels:
    app: vector
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: vector
  template:
    metadata:
      labels:
        app: vector
    spec:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/ingress
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
      - name: time 
        hostPath:
          path: /etc/localtime
      - configMap:
          defaultMode: 420
          items:
          - key: vector.toml 
            path: vector.toml
          name: vector
        name: vector
      containers:
      - name: vector
        image: timberio/vector:latest-alpine
        args: ["-c", "/etc/vector/vector.toml"]
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: /etc/localtime 
          name: time
          readOnly: False
        - mountPath: /etc/vector/
          name: vector
          readOnly: true
